### ISSUE TITLE
Request for compiled JPL file for direct installation.

### ISSUE THREAD

**Issue by debabratadas** [SeptemberHX/joplin-plugin-bundle#1]
Please include the compiled JPL file in your releases. Thanks

**Comment by SeptemberHX** [comment]
Hello, you can always download the compiled plugin file with the latest version on: https://github.com/joplin/plugins

Also, you can install/update the plugin directly in the Joplin settings -> plugins

**Comment by debabratadas** [comment]
Found it, I was searching for "Joplin Plugin Bundle" instead of just "Plugin Bundle". Thanks.
