### ISSUE TITLE
The to do plug-in always goes round and round, and it will be better if you restart it. This problem will occur again later.

### ISSUE THREAD

**Issue by Benjamin-Watson0** [SeptemberHX/joplin-plugin-bundle#13]
The to do plug-in always goes round and round, and it will be better if you restart it. This problem will occur again later.
[![P229U.png](https://s1.328888.xyz/2022/10/04/P229U.png)](https://imgloc.com/i/P229U)
<https://discourse.joplinapp.org/t/plugin-sidebar-plugin-bundles-v0-5-1-2022-09-25/27062/90?u=benjamin-watson0>

**Comment by SeptemberHX** [comment]
It will show the loading image when you open and close Joplin settings. It should work again when you select another note.

If not, please toggle the dev tools through `Tools`, and check whether there have error outputs in red color.

**Comment by Benjamin-Watson0** [comment]
Now I understand, good!!

**Comment by SeptemberHX** [comment]
For the show/hide button, you can try the new build version. A new button is added to the note toolbar to toggle the sidebar on/off

[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9703420/com.septemberhx.pluginBundle.jpl.zip)

**Comment by Benjamin-Watson0** [comment]
I tried it, and it seems to work well, but when the sidebar is turned on and off, the space he pops up is too large. (I remember it was the software [itself.)
https://remain-files.oss-cn-beijing.aliyuncs.com/test/iobiDduoCI.mp4
