### ISSUE TITLE
Bugs: Related Notes not work on Linux

### ISSUE THREAD

**Issue by SeptemberHX** [SeptemberHX/joplin-plugin-bundle#14]
Bugs: Related Notes not work on Linux. And windows is also reported.

**Comment by bepolymathe** [comment]
Hi @SeptemberHX 

I just tried the new version but I still have the same behavior. 

```
plugin_com.septemberhx.pluginBundle.js:315          GET https://api.zotero.org/users/454202/items/MSEHZ3VC/children?format=json 400 (Bad Request)
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
r @ plugin_com.septemberhx.pluginBundle.js:315
o @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
t @ plugin_com.septemberhx.pluginBundle.js:3
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
r @ plugin_com.septemberhx.pluginBundle.js:315
o @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
t @ plugin_com.septemberhx.pluginBundle.js:3
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
L @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
n @ plugin_com.septemberhx.pluginBundle.js:315
getAnnotation @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
n @ plugin_com.septemberhx.pluginBundle.js:3
getAnnotation @ plugin_com.septemberhx.pluginBundle.js:3
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
n @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
setTimeout (async)
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
c @ plugin_com.septemberhx.pluginBundle.js:3
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
n @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
setTimeout (async)
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
c @ plugin_com.septemberhx.pluginBundle.js:3
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
n @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_index.js:92
emit @ node:events:390
onMessage @ node:electron/js2c/renderer_init:69
plugin_com.septemberhx.pluginBundle.js:315 Uncaught (in promise) Error: 400: Bad Request
    at plugin_com.septemberhx.pluginBundle.js:315:378196
    at Generator.next (<anonymous>)
    at r (plugin_com.septemberhx.pluginBundle.js:315:388092)
    at o (plugin_com.septemberhx.pluginBundle.js:315:388291)
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
r @ plugin_com.septemberhx.pluginBundle.js:315
o @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
n @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
setTimeout (async)
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
c @ plugin_com.septemberhx.pluginBundle.js:3
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
s @ plugin_com.septemberhx.pluginBundle.js:315
Promise.then (async)
d @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
n @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
setTimeout (async)
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:3
c @ plugin_com.septemberhx.pluginBundle.js:3
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
n @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_com.septemberhx.pluginBundle.js:315
(anonymous) @ plugin_index.js:92
emit @ node:events:390
onMessage @ node:electron/js2c/renderer_init:69
```

![image](https://user-images.githubusercontent.com/29939805/193784275-87428a21-1eb3-4526-90d3-0491652810b2.png)

**Comment by SeptemberHX** [comment]
[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9712606/com.septemberhx.pluginBundle.jpl.zip)

Please try again with the new version to check whether these error messages show again. They should disappear now.

However, only the last error of `parent_id` is related to the `Related Note`. Hope it can fix the problem.

**Comment by bepolymathe** [comment]
Sorrry but same bahavior with this version without logs... 

[Capture vidéo du 05-10-2022 06:34:13.webm](https://user-images.githubusercontent.com/29939805/193982153-df3f0173-8db2-4cc0-888c-cb70921692ef.webm)

**Comment by SeptemberHX** [comment]
Strange... I will test it again on Windows11

**Comment by SeptemberHX** [comment]
Sadly, no. I tested it on both Window11 22H2 and Ubuntu 22.04, and they all worked fine.

Maybe it is related to the content of notes? Can you test it with a new installed joplin without user notes?

**Comment by bepolymathe** [comment]
Yes you are right. I tried to start with an empty new "Test" profile and everything seems to be working normally.

![image](https://user-images.githubusercontent.com/29939805/195525013-34c2c5c5-3ba8-4843-9ede-49eda307932c.png)

Are there characters that could cause problems in the titles ? I sometimes have emojis in the note or notebook titles for example...

**Comment by bepolymathe** [comment]
I spoke too quickly. The problem comes up even with these two notes alone.


![image](https://user-images.githubusercontent.com/29939805/195528176-4611a8fc-5da4-47be-9b0d-49b8464cc8e5.png)

Perhaps a compatibility problem with another plugin ?

**Comment by SeptemberHX** [comment]
I will check the red error message first. It is more likely the reason that causes this bug.

**Comment by SeptemberHX** [comment]
[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9785875/com.septemberhx.pluginBundle.jpl.zip)

This should fix the 'parent_id' error. However, it seems does not affect the function even with this error.

What other plugins do you install? I still cannot reproduce this problem

**Comment by bepolymathe** [comment]
[Capture vidéo du 14-10-2022 20:23:22.webm](https://user-images.githubusercontent.com/29939805/195915444-c0b4da14-e9d8-47bb-8280-2e7cb7874ec5.webm)

**Comment by bepolymathe** [comment]
What do you think about this comment about Quirks Mode ?

![image](https://user-images.githubusercontent.com/29939805/195917122-a3faf76c-41f1-484f-aa68-a9c54b57a6bc.png)

**Comment by SeptemberHX** [comment]
I also have the `Quirks Mode` message, but it works fine.

It is really lots of plugins you have installed... It would be nice if you can disable all other plugins to test whether where is a conflict between this and other plugins.

Or, create a new windows user and switch to the new user. You should get a clean new Joplin without plugins. And you can safely delete the new created user after testing.

**Comment by bepolymathe** [comment]
I tried to deactivate and then uninstall all the plugins but that doesn't change anything. This thing is hell. Not a clue to where it can come from... 🤔

**Comment by bepolymathe** [comment]
New message. 

![image](https://user-images.githubusercontent.com/29939805/196127863-a2366d7b-d833-4c46-bf4b-ffad0da3599e.png)

**Comment by SeptemberHX** [comment]
This should be caused by the Papers plugin when it fails to parse the date from your zotero item. I will fix it soon.

**Comment by SeptemberHX** [comment]
Have you tried to disable other sub-plugins and only enable Related Notes? It is possible that other sub-plugins break the initialization of Related Notes

**Comment by bepolymathe** [comment]
Yes 

> I tried to deactivate and then uninstall all the plugins but that doesn't change anything. This thing is hell. Not a clue to where it can come from... 🤔

**Comment by SeptemberHX** [comment]
I mean disable other features provided by `joplin-plugin-bundle`: `Outline`, `Inline Todo`, `Papers`, etc.

**Comment by bepolymathe** [comment]
Okay, sorry, I read too quickly. Indeed, it is "papers" that is the problem. It works if it deactivates it.
 
This is the situation under windows. I need to try on linux tonight.

**Comment by bepolymathe** [comment]
> I need to try on linux tonight.

The problem persist on linux... 

![image](https://user-images.githubusercontent.com/29939805/197626800-daa63001-4fa9-4c4f-b7f2-08e37b0ee0e1.png)

**Comment by bepolymathe** [comment]
A screenshot with the new version using papers

![image](https://user-images.githubusercontent.com/29939805/198543406-bbd7e2cb-cc2b-4ce0-aa37-3bbdaaac1474.png)
