### ISSUE TITLE
Feature request: related notes filters

### ISSUE THREAD

**Issue by alondmnt** [SeptemberHX/joplin-plugin-bundle#15]
Love this feature, but please consider a couple of minor improvements:

1. Add a filter based on the type of link (forward / backward, maybe also distinguish internal / external?).
2. For forward / outgoing links, add a way to jump to the line in the current note where the link appears.
3. For backward / incoming links, add a way to jump to the corresponding line in the referrer note (like the note link system plugin does).

Thanks!

**Comment by SeptemberHX** [comment]
1 is ok.

2 and 3: I haven't came up with a good idea for this when one note is mentioned for several times. Always scroll to the line that it appears for the first time?

**Comment by alondmnt** [comment]
Thanks for considering this!

As for 2 and 3: I suppose that jumping to the first appearance is already pretty awesome. From a UX perspective (it may be too cumbersome to implement and maintain), I can imagine that clicking multiple times on the item can switch between appearances. First click on the panel brings the cursor to the first line, second click switches to the second line, ..., and finally back to the first, etc.

**Comment by SeptemberHX** [comment]
> As for 2 and 3: I suppose that jumping to the first appearance is already pretty awesome. From a UX perspective (it may be too cumbersome to implement and maintain), I can imagine that clicking multiple times on the item can switch between appearances. First click on the panel brings the cursor to the first line, second click switches to the second line, ..., and finally back to the first, etc.

No... The list in related note is changed when you click any of them. A new note is opened, and the related note tab is refreshed. The users don't have the change to click the same item anymore

**Comment by alondmnt** [comment]
For 3: You're completely right, I didn't think this through.
For 2: I was imagining jumping to the line in the currently opened note where the forward link appears. If this requires reloading the note (and then refreshing the tab) in order to scroll to the desired line, then this is indeed an obstacle.

BTW, the way note link system solved this was to have multiple entries on the panel that link back to each reference, but I'm afraid this may clutter the space on the tab too much.

If you think that taking only the first appearance into account is a good enough solution, then I'll certainly be a happy user. :) Otherwise, it's not a very crucial feature.

**Comment by alondmnt** [comment]
This is really awesome, thank you!!

I'm not sure, though, that I understand how to jump to the first appearance. I tried pressing the arrow next to the related notes title, and nothing happened (v0.5.2 from the plugin store).

**Comment by SeptemberHX** [comment]
[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9893954/com.septemberhx.pluginBundle.jpl.zip)

I just redesigned the UI, and you can test it with the attachment.

Now, there are four tabs in related notes:
1. Note lists that contains current note's id
2. Note lists that contains current note's title
3. Note lists whose ids appear in current
4. Note lists whose titles appear in current

All the appearances are lists with collapsable items now, and 1 & 2 are in blue color, and 3 & 4 are in green color.

You can click on any of the appeared line to jump to that line, and right click on the note title only to just open that note

**Comment by alondmnt** [comment]
Cool! I like this new approach. It's fairly easy to navigate based on the little time I had to test it.
I suggest adding a setting for opening/closing all the collapsing items by default. Some users may find this de-cluttering useful.

**Comment by alondmnt** [comment]
Just wanted to say that I'm really enjoying the latest dev-build of the plugin (with the new filters). I noticed that you've been away recently, and I'm wondering if there is a plan to officially release a version sometime.

**Comment by SeptemberHX** [comment]
I planned to release next version when the another milestone is reached, but recently I am busy with my school life. I will be back at the end of the semester (in one month I think). I will also release a new version with current commits now. 😄

**Comment by alondmnt** [comment]
Thanks a lot! And good luck with the semester!
