### ISSUE TITLE
对zotero进行链接的使用方式

### ISSUE THREAD

**Issue by buriedms** [SeptemberHX/joplin-plugin-bundle#17]
我非常感兴趣对zotero支持的功能，请问有具体的使用方式案例吗？不是很理解如何使用，谢谢！

**Comment by buriedms** [comment]
在基础上，其实我很期待这一个功能：
不仅仅只是跳转链接，更可以实现在zotero上撰写的笔记，可以导入到joplin当中观看并且修改，也就是说两者之间是相互同步的！
我认为这个功能能够将两个软件极大程度上的结合起来使用，当然不知道能够方便实现，万分感谢您在争取joplin和zotero之间的相互链接使用！

**Comment by SeptemberHX** [comment]
实现倒是不成问题，主要问题是怎么处理 zotero 笔记在 joplin 中的存储、展现方式。

如果以普通笔记的形式，那就意味着能在任意地方同步一条 zotero 的笔记过来，但是 zotero 中一篇论文的笔记可以有多个，不是一对一的，会导致笔记很零散。

技术上也不能把一篇文献的所有笔记都放在一个 joplin 笔记中，因为永远不能相信用户的操作是符合规则的。

**Comment by SeptemberHX** [comment]
使用的话，
1. 设置 -> bundle -> enable papers
2. 然后重启 joplin，再进入 设置 -> papers，选择 zotero 服务方式，然后按照设置说明中的 url 填上 API key 和 user id，重启 joplin。
3. 菜单 -> Tools -> papers -> create notes for paper，选一篇然后确定就能创建了。选中这篇笔记，侧栏中的 papers tab 会自动显示相关内容

**Comment by SeptemberHX** [comment]
同步到笔记好像不太行，主要原因是 zotero 的笔记是用 html 存储的，joplin 的是 markdown，没办法直接同步；如果进行转换，那么格式就不能完全统一了，可能会导致很多奇奇怪怪的 不过

**Comment by buriedms** [comment]
好的好的，十分感谢！
感谢你热情帮助！十分感谢！

发自我的iPhone

**Comment by buriedms** [comment]
报告一个问题：侧边栏显示发生了遮挡
![image](https://user-images.githubusercontent.com/55041393/195972431-116d6272-292c-4631-b1d4-b73bb16cedf9.png)

提供一个小建议：
导入zotero笔记可否在自己当前所在的目录下创建，现在已有的是创建在papers/years目录下，但是这种并不能让我对我的论文有更好的区分效果，我更希望的导入后论文在自己创建的论文分类目录结构下，以便于自己的快速检索和区分

**Comment by SeptemberHX** [comment]
这个是因为目前有个最小的宽度限制（对于一些插件来说，太窄的显示效果实在太糟糕了），但是插件宽度是 joplin 控制的，插件自己没法设置。

等后续我想要的功能都完善后，看看能不能再改善一下吧，优先级比较低，因为一般不会调整到这个窄。如果你的屏幕空间比较紧张，可以把它放到 Joplin 目录的下面，这样能宽不少。

> 我更希望的导入后论文在自己创建的论文分类目录结构下，以便于自己的快速检索和区分

这个有一点困难：zotero 是允许一篇论文在多个分类下的。如果按照 zotero 的分类来放，这种情况就没法处理了

**Comment by buriedms** [comment]
后者如果是创建在joplin当中的当前目录下，这个可能实现嘛？

发自我的iPhone

**Comment by SeptemberHX** [comment]
这个可以，后面我可以加个默认关闭的设置，开启后就直接创建在当前目录下

**Comment by buriedms** [comment]
万分感谢！

**Comment by SeptemberHX** [comment]
现在可以将笔记直接创建到当前文件夹了，默认是开启的，可以在设置中关闭。新版本见附件。

[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/10253494/com.septemberhx.pluginBundle.jpl.zip)
