### ISSUE TITLE
Feature Request: Toggle Side Panel on and off

### ISSUE THREAD

**Issue by quantumfate** [SeptemberHX/joplin-plugin-bundle#22]
I love this side panel, it is essential as I like to have a table of contents that I can look into when I need to. I don't like that there is no option for toggeling the panel on and off as you can with other panels. On my laptop I have limited space on my screen and I need to have a PDF open as I am writing my notes, or when I follow lectures.

Besides being able to toggle the side panel on and off it would be great to have an opton to hide the panel automatically when no other side panels are toggled on.

If that is not possible (or additionally) you could bind the toggling on/off to a shortcut so users can create macros to combine toggling on/off side panels that have a shortcut

**Comment by SeptemberHX** [comment]
A button to toggle on/off the panel is already added to the repo: 6479c3b6f944dbed32677fdc3e04c9a75f17dd19
I will try to add a shortcut for the button.

I think it is not possible to check whether there are other panels because no such a API is provided by the Joplin.

**Comment by SeptemberHX** [comment]
[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9838628/com.septemberhx.pluginBundle.jpl.zip)

You can test it with the attached file.
