### ISSUE TITLE
Bugs : [Todo] Link in task description crash the sidebar

### ISSUE THREAD

**Issue by bepolymathe** [SeptemberHX/joplin-plugin-bundle#25]
Hi @SeptemberHX 

If you add a link to a note in the description...

[Capture vidéo du 28-10-2022 10:55:58.webm](https://user-images.githubusercontent.com/29939805/198547486-ca055737-3b59-4f5f-9f62-afff9229f546.webm)

**Comment by SeptemberHX** [comment]
[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9887733/com.septemberhx.pluginBundle.jpl.zip)

It should be fixed now.

**Comment by bepolymathe** [comment]
👍
