### ISSUE TITLE
Creates a new notebook every time a daily note is added

### ISSUE THREAD

**Issue by DKBurns** [SeptemberHX/joplin-plugin-bundle#3]
Hi there, great idea with this plugin. however, every time I click on the calendar it makes an entirely new notebook!

![image](https://user-images.githubusercontent.com/31402390/188579197-8bd1683a-02b8-4b24-a089-f20b2e211c7a.png)

Then clicking the same date again:

![image](https://user-images.githubusercontent.com/31402390/188579268-1f163efd-12f3-4a4e-a64d-83f518616097.png)

then if I click ok

![image](https://user-images.githubusercontent.com/31402390/188579347-905525d0-db95-4738-8c00-9e801f2c9d80.png)

I wonder if I'm doing something wrong/badly, but it looks like a bug to me?

Thanks again for this great idea for a plugin, hopefully it's an easy fix!

**Comment by SeptemberHX** [comment]
I think I figure it out. Can you try the attached new build plugin?

[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9494725/com.septemberhx.pluginBundle.jpl.zip)

**Comment by DKBurns** [comment]
> I think I figure it out. Can you try the attached new build plugin?
> 
> [com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9494725/com.septemberhx.pluginBundle.jpl.zip)

Yep that works! that was a very quick fix!
