### ISSUE TITLE
bug: Plugin Bundle  todo load no in 'Daily Note' item

### ISSUE THREAD

**Issue by ymzk64** [SeptemberHX/joplin-plugin-bundle#32]
I have other note not in 'Daily Note' folder, but have checkbox in the note
then todo show the item
<img width="263" alt="image" src="https://user-images.githubusercontent.com/117650018/230760073-66f74267-8bec-4505-be31-12cbf016d4c7.png">

this item not in folder 'Daily Note' and I setting
<img width="475" alt="image" src="https://user-images.githubusercontent.com/117650018/230760109-9cfba329-5c1b-42bd-8abb-b96233d6b29f.png">

then no fix, todo same show the 'test' item..

**Comment by SeptemberHX** [comment]
Do you mean you don't want to see todo items in some specific notes?

If so, you should go to `settings -> Bundle inline todo -> tags`. The plugin can overlook all the todo items in the notes with the tags you set in the settings.

**Comment by ymzk64** [comment]
Sorry, My Joplin Setting Page no this `settings -> Bundle inline todo -> tags`
<img width="889" alt="image" src="https://user-images.githubusercontent.com/117650018/230768277-63224221-65d2-474b-85ae-a1b9c1f6d39b.png">
and I use 0.5.4 ver
<img width="315" alt="image" src="https://user-images.githubusercontent.com/117650018/230768314-4d43a321-9c73-44c0-948a-e91e4027d646.png">
I hope todo feature only get from  'Daily Note' folder not all note

**Comment by SeptemberHX** [comment]
Oh, my bad. This feature was implemented but not published yet.

However, you can only ignore notes by setting tags. The feature you require is currently not supported.

**Comment by ymzk64** [comment]
Can I ask when it will be released?
So at that time, just add the corresponding tag (and the position you mentioned) to the article to make the article be ignored?
Am I right?
Thanks

**Comment by SeptemberHX** [comment]
I just published v0.5.5. You can find it in Joplin plugin repo in 1 hour I think.

**Comment by ymzk64** [comment]
Thank you for your prompt assistance.

**Comment by ymzk64** [comment]
I just tested it and it worked as you said
grateful
