### ISSUE TITLE
Feature: Add #joplin topic to github project About

### ISSUE THREAD

**Issue by ChrisWeiss** [SeptemberHX/joplin-plugin-bundle#34]
Your project would be more findable if you added the #joplin topic to the projects About information.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by SeptemberHX** [comment]
Thanks for the tips! I just added the #joplin and #joplin-plugin in the repo description :)
