### ISSUE TITLE
Selecting All Projects in TODO displays tasks without a project

### ISSUE THREAD

**Issue by alondmnt** [SeptemberHX/joplin-plugin-bundle#5]
I expected the filter page to show all tasks related to any project upon selecting All Projects, excluding the tasks shown when selecting No Project. If this was the intended behavior, then please consider this a feature request to add a way to filter out tasks that have no defined project.

Thanks!

**Comment by SeptemberHX** [comment]
`All Project` is used to show all the tasks (with & without project).

I will add a `With Project` to filter out tasks without project.

**Comment by alondmnt** [comment]
Thank you!

**Comment by SeptemberHX** [comment]
v0.5.0 has the `withProject` filter
