### ISSUE TITLE
Outline  不随着滚动高亮显示当前标题

### ISSUE THREAD

**Issue by SeptemberHX** [SeptemberHX/joplin-plugin-bundle#7]
https://discourse.joplinapp.org/t/plugin-sidebar-plugin-bundles-v0-4-2-2022-09-10/27062/56?u=septemberhx

**Comment by SeptemberHX** [comment]
Joplin -> 帮助 -> 打开开发者模式 查看是否有任何错误信息（标红的地方）

**Comment by Benjamin-Watson0** [comment]
我该怎么整？你说的是打开开发者工具？
![图片](https://user-images.githubusercontent.com/112467275/189788099-a0ef6f27-a15c-4aa4-b1f5-30394aeef417.png)

**Comment by SeptemberHX** [comment]
> 我该怎么整？你说的是打开开发者工具？ ![图片](https://user-images.githubusercontent.com/112467275/189788099-a0ef6f27-a15c-4aa4-b1f5-30394aeef417.png)

<img width="320" alt="image" src="https://user-images.githubusercontent.com/18042424/189788547-34c444c3-1a70-4e6b-a427-e14e968cd901.png">

选 console，然后往回翻信息，看看有没有红色的。如果信息太多了，那就重启一下 joplin 然后再看看

**Comment by Benjamin-Watson0** [comment]
有很多红的。

![图片](https://user-images.githubusercontent.com/112467275/189789136-df19e257-33db-48d4-ba04-fd2a9a241a15.png)

**Comment by SeptemberHX** [comment]
试试看附件里新打包的：

[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9552877/com.septemberhx.pluginBundle.jpl.zip)

**Comment by Benjamin-Watson0** [comment]
现在问题解决了。

https://user-images.githubusercontent.com/112467275/189790281-493115cf-26ec-4391-b614-1759e60b9bd8.mp4
