### ISSUE TITLE
日历放大正常，缩小看不到右侧信息

### ISSUE THREAD

**Issue by buriedms** [SeptemberHX/joplin-plugin-bundle#8]
![image](https://user-images.githubusercontent.com/55041393/189900910-f0fdbd8f-eeb2-4429-aaae-f57589623af9.png)
日历缩小之后，旁边的日期看不到了。

另外提两个建议。
1.侧栏有大量的空间浪费了，可以的话，希望这个贴靠的区域可以选择上方或者下方以减少空间的浪费。
2.可是尝试集成以下 Note tap的功能不，感觉目前的功能正好缺少打开一定的标签日记这些工具

**Comment by SeptemberHX** [comment]
日历这个是因为每个格子有最小宽度导致的，后面我可以去掉。

其它：
1. 可以通过菜单 -> 视图 -> 更改应用布局 来调整位置，这个是 Joplin 的功能，插件本身是不能决定自己在哪的
2. 不会考虑的，note tab 插件放在上方更符合操作习惯，而不是像现在已有的插件一样放在左右两侧，所以没必要放进来

**Comment by buriedms** [comment]
是的，我发现使用了这个视图更改之后，我的基本所有问题都解决了！彻底解决了我的插件只能放在左右两侧的问题，非常感谢你的帮助。这个插件对我的帮助十分的大，再次非常感谢你！我会帮你积极的推广一下！

另外有个小建议：是否可以设置改变通过日历创建的文件的类别格式？一般情况下可能更习惯创建一个代办事项的文件。

**Comment by SeptemberHX** [comment]
待办事项的文件是啥意思，有具体的命名规则吗？

**Comment by buriedms** [comment]
![image](https://user-images.githubusercontent.com/55041393/190148944-ae0380fc-81f6-4e3e-a947-9d97d4465b1d.png)
就比如这样，前两个是我更换类型是代办事项类型（to-do)，后两个仍旧还是笔记类型(note)

**Comment by buriedms** [comment]
![image](https://user-images.githubusercontent.com/55041393/190148944-ae0380fc-81f6-4e3e-a947-9d97d4465b1d.png)
就比如这样，前两个是我更换类型是代办事项类型（to-do)，后两个仍旧还是笔记类型(note)

**Comment by SeptemberHX** [comment]
新建每日笔记时，普通笔记、todo笔记类型在设置里可以设置了

[com.septemberhx.pluginBundle.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-bundle/files/9567358/com.septemberhx.pluginBundle.jpl.zip)
