### ISSUE TITLE
由于出了点儿问题，导致再次安装总是不成功

### ISSUE THREAD

**Issue by buriedms** [SeptemberHX/joplin-plugin-bundle#9]
显示图片结果如下：
![image](https://user-images.githubusercontent.com/55041393/190239078-8d8fce0f-276a-4fae-a133-755156f0764f.png)

不太清楚如何解决。重新安装始终不成功。

**Comment by SeptemberHX** [comment]
这个不太清楚，我不用 Windows 所以没办法提供帮助。试试从 Joplin 的设置里直接安装插件？
